const B = (cat, question, options, answer, explanation) => ({ cat, question, options, answer, explanation });

module.exports = [
  B('html', 'Which tag is used to create a hyperlink in HTML?', ['a', 'link', 'href', 'url'], 0, 'The a (anchor) tag with the href attribute creates a link.'),
  B('html', 'Which input type shows a date picker?', ['text', 'date', 'calendar', 'time'], 1, 'input type="date" gives a date picker in modern browsers.'),
  B('html', 'Which tag sets the title shown on the browser tab?', ['h1', 'title', 'header', 'meta'], 1, 'The title tag inside head sets the tab title.'),
  B('html', 'Which semantic element is meant for a group of navigation links?', ['nav', 'div', 'list', 'section'], 0, 'nav marks the main navigation block.'),
  B('html', 'Which attribute makes a form field mandatory?', ['required', 'mandatory', 'validate', 'needed'], 0, 'required stops form submission when the field is empty.'),
  B('html', 'Which tag creates a numbered list?', ['ol', 'ul', 'li', 'dl'], 0, 'ol is an ordered (numbered) list; ul is unordered.'),
  B('html', 'Data stored in sessionStorage is cleared when:', ['The tab is closed', 'The computer restarts only', 'One hour passes', 'Never'], 0, 'sessionStorage lasts only for the tab session.'),
  B('html', 'Which tag embeds another web page inside the current page?', ['embed page', 'iframe', 'frame set', 'include'], 1, 'iframe embeds an external document such as a map or video.'),

  B('css', 'Which CSS property makes text bold?', ['font-style', 'font-weight', 'text-bold', 'text-style'], 1, 'font-weight: bold makes text bold.'),
  B('css', 'Which selector targets the element with id="main"?', ['.main', '#main', 'main', '*main'], 1, '# selects by id and . selects by class.'),
  B('css', 'Which display value creates a flex container?', ['flex', 'block-flex', 'flexible', 'box'], 0, 'display: flex turns the element into a flex container.'),
  B('css', 'What is the default value of the position property?', ['relative', 'absolute', 'static', 'fixed'], 2, 'Elements are static unless you change it.'),
  B('css', 'Which unit is relative to the root element font size?', ['em', 'rem', 'px', 'vh'], 1, 'rem is based on the font size of the html element.'),
  B('css', 'Which property sets the space between flex or grid items?', ['gap', 'margin-all', 'spacing', 'space-between'], 0, 'gap adds space between items in flex and grid layouts.'),
  B('css', 'Which pseudo-class applies styles when the mouse is over an element?', [':active', ':hover', ':focus', ':visited'], 1, ':hover matches while the pointer is over the element.'),
  B('css', 'Which property controls the stacking order of positioned elements?', ['order', 'z-index', 'stack', 'layer'], 1, 'A higher z-index appears on top.'),
  B('css', 'Which has the highest specificity?', ['Element selector', 'Class selector', 'Id selector', 'Inline style'], 3, 'Inline style beats id, class and element selectors (except !important).'),
  B('css', 'Which declaration hides an element but keeps its space in the layout?', ['display: none', 'visibility: hidden', 'opacity: 1', 'position: static'], 1, 'visibility: hidden hides it while the space remains; display: none removes it.'),

  B('javascript', 'What does console.log(typeof undefined) print?', ['null', 'undefined', 'object', 'error'], 1, 'typeof undefined is the string "undefined".'),
  B('javascript', 'What does console.log(2 + "3") print?', ['5', '23', '6', 'NaN'], 1, 'With a string operand + joins text, giving "23".'),
  B('javascript', 'What does console.log("5" - 2) print?', ['52', '3', 'NaN', '7'], 1, 'The - operator converts the string to a number, so 5 - 2 = 3.'),
  B('javascript', 'What does console.log(0.1 + 0.2 === 0.3) print?', ['true', 'false', 'undefined', 'error'], 1, 'Floating-point precision makes 0.1 + 0.2 slightly more than 0.3.'),
  B('javascript', 'Which method converts a JSON string into an object?', ['JSON.stringify', 'JSON.parse', 'JSON.object', 'JSON.convert'], 1, 'JSON.parse turns text into an object; stringify does the opposite.'),
  B('javascript', 'Which array method returns a new array with only the elements that pass a test?', ['map', 'filter', 'reduce', 'forEach'], 1, 'filter keeps the elements for which the callback returns true.'),
  B('javascript', 'What does console.log(null == undefined) print?', ['true', 'false', 'error', 'null'], 0, 'Loose equality treats null and undefined as equal.'),
  B('javascript', 'What does console.log(null === undefined) print?', ['true', 'false', 'error', 'undefined'], 1, 'Strict equality also compares types, and they differ.'),
  B('javascript', 'What does [1, 2, 3].map(x => x * 2) return?', ['[1, 2, 3]', '[2, 4, 6]', '6', '[2, 4]'], 1, 'map applies the function to every element.'),
  B('javascript', 'What does [1, 2, 3, 4].reduce((a, b) => a + b, 0) return?', ['4', '10', '24', '0'], 1, 'The reducer adds all values: 1 + 2 + 3 + 4 = 10.'),
  B('javascript', 'Which keyword declares a variable that cannot be reassigned?', ['let', 'var', 'const', 'static'], 2, 'const bindings cannot be reassigned.'),
  B('javascript', 'What does console.log(typeof NaN) print?', ['NaN', 'number', 'undefined', 'string'], 1, 'NaN is a special value of the number type.'),
  B('javascript', 'An async function always returns:', ['A string', 'A Promise', 'undefined', 'A callback'], 1, 'The return value is wrapped in a Promise.'),
  B('javascript', 'What does console.log([] + []) print?', ['[]', '0', 'An empty string', 'undefined'], 2, 'Both arrays convert to empty strings, and joining them gives an empty string.'),
  B('javascript', 'Which method stops a form from reloading the page on submit?', ['stopPropagation()', 'preventDefault()', 'return null', 'cancel()'], 1, 'event.preventDefault() blocks the default form submission.'),

  B('react', 'What does JSX stand for?', ['JavaScript XML', 'Java Syntax Extension', 'JSON XML', 'JavaScript Extra'], 0, 'JSX lets you write HTML-like syntax in JavaScript.'),
  B('react', 'Which special prop should each item in a rendered list have?', ['id', 'key', 'ref', 'index'], 1, 'A unique key helps React track list items.'),
  B('react', 'When does useEffect(() => {...}, []) run?', ['On every render', 'Once after the first render', 'Never', 'Only on unmount'], 1, 'An empty dependency array runs the effect once after mount.'),
  B('react', 'How does a parent component pass data to a child?', ['Using props', 'Using cookies only', 'Using CSS', 'Using the DOM'], 0, 'Props flow from parent to child.'),
  B('react', 'What happens when a state setter such as setCount is called with a new value?', ['The component re-renders', 'The page reloads', 'Nothing', 'The server is called'], 0, 'A state change schedules a re-render.'),
  B('react', 'Which hook reads a value from a Context?', ['useState', 'useContext', 'useMemo', 'useReducer'], 1, 'useContext returns the current context value.'),
  B('react', 'Why does JSX use className instead of class?', ['class is a reserved word in JavaScript', 'It is faster', 'It is an old HTML rule', 'It is a typo'], 0, 'class is reserved in JS, so React uses className.'),
  B('react', 'Which react-router component navigates without a full page reload?', ['a', 'Link', 'Anchor', 'Href'], 1, 'Link changes the route on the client side.'),
  B('react', 'Which hook keeps a mutable value between renders without causing a re-render?', ['useRef', 'useState', 'useEffect', 'useContext'], 0, 'Changing ref.current does not trigger a render.'),
  B('react', 'What is the Virtual DOM?', ['A lightweight in-memory copy of the real DOM', 'A browser plugin', 'A CSS framework', 'A database'], 0, 'React compares virtual trees and updates only the changed parts.'),

  B('nodejs', 'Which JavaScript engine does Node.js use?', ['SpiderMonkey', 'V8', 'Chakra', 'Rhino'], 1, 'Node.js runs on Chrome V8 engine.'),
  B('nodejs', 'Which built-in Node module is used to work with files?', ['fs', 'http only', 'path only', 'file'], 0, 'fs provides file system functions.'),
  B('nodejs', 'Which Express method handles HTTP GET requests?', ['app.fetch', 'app.get', 'app.read', 'app.load'], 1, 'app.get(path, handler) handles GET.'),
  B('nodejs', 'Which built-in Express middleware parses JSON request bodies?', ['express.json()', 'express.body()', 'express.parse()', 'express.data()'], 0, 'express.json() fills req.body with parsed JSON.'),
  B('nodejs', 'Which HTTP status code means Unauthorized?', ['400', '401', '403', '404'], 1, '401 means authentication is missing or invalid.'),
  B('nodejs', 'Which package is commonly used to hash passwords in Node.js?', ['bcrypt', 'express', 'nodemon', 'cors'], 0, 'bcrypt hashes passwords safely with a salt.'),
  B('nodejs', 'Which command installs a package from npm?', ['npm get name', 'npm install name', 'npm add-file name', 'node install name'], 1, 'npm install name downloads it into node_modules.'),
  B('nodejs', 'What is process.env used for in Node.js?', ['Reading environment variables', 'Listing files', 'Starting a server', 'Compiling code'], 0, 'It holds environment variables such as PORT or secrets.'),

  B('webfund', 'What does HTTP status 301 mean?', ['OK', 'Moved Permanently', 'Bad Request', 'Server Error'], 1, '301 is a permanent redirect.'),
  B('webfund', 'What does CORS stand for?', ['Cross-Origin Resource Sharing', 'Client Origin Request Security', 'Cross-Object Rendering System', 'Central Origin Routing Service'], 0, 'CORS lets a server allow requests from other origins.'),
  B('webfund', 'Which HTTP method is normally used to replace an existing resource completely?', ['GET', 'PUT', 'HEAD', 'OPTIONS'], 1, 'PUT replaces the resource; PATCH updates part of it.'),
  B('webfund', 'Which browser storage is automatically sent to the server with every request?', ['localStorage', 'sessionStorage', 'Cookies', 'IndexedDB'], 2, 'Cookies are attached to matching requests automatically.'),
  B('webfund', 'Which Git command saves staged changes to the local repository?', ['git push', 'git commit', 'git pull', 'git clone'], 1, 'git commit records a snapshot locally.'),
  B('webfund', 'Which Git command fetches and merges changes from the remote repository?', ['git pull', 'git init', 'git add', 'git status'], 0, 'git pull is fetch plus merge.'),
  B('webfund', 'What does XSS stand for?', ['Cross-Site Scripting', 'Extra Style Sheets', 'XML Server Security', 'Cross-Server Sync'], 0, 'XSS injects malicious scripts into web pages.'),
  B('webfund', 'Which technique best prevents SQL injection?', ['Parameterized queries', 'Longer passwords', 'Using HTTPS only', 'Hiding the database'], 0, 'Parameterized queries keep user input separate from SQL code.'),
  B('webfund', 'A JWT is best described as:', ['A signed token that carries user claims', 'A database', 'A CSS file', 'A type of cookie only'], 0, 'The server signs it so the token cannot be changed unnoticed.'),
  B('webfund', 'Which HTTP header normally carries a Bearer token?', ['Content-Type', 'Authorization', 'Accept', 'Host'], 1, 'Authorization: Bearer <token> is the standard form.')
];