const B = (cat, question, options, answer, explanation) => ({ cat, question, options, answer, explanation });

module.exports = [
  B('dsa', 'What is the time complexity of binary search on a sorted array of n elements?', ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'], 1, 'The search range halves every step, so it takes log n steps.'),
  B('dsa', 'Which data structure follows the LIFO principle?', ['Queue', 'Stack', 'Array', 'Tree'], 1, 'In a stack the last element pushed is the first to be popped.'),
  B('dsa', 'What is the worst-case time complexity of quick sort?', ['O(n log n)', 'O(n^2)', 'O(n)', 'O(log n)'], 1, 'With very bad pivots (for example an already sorted array and a first-element pivot) it degrades to O(n^2).'),
  B('dsa', 'Which traversal of a binary search tree gives the elements in sorted order?', ['Preorder', 'Inorder', 'Postorder', 'Level order'], 1, 'Inorder visits left, root, right, which gives ascending order in a BST.'),
  B('dsa', 'Which data structure is used in breadth-first search (BFS)?', ['Stack', 'Queue', 'Heap', 'Set'], 1, 'BFS visits nodes level by level, which needs a queue.'),
  B('dsa', 'What is the average time complexity of a hash table lookup?', ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'], 0, 'A good hash function gives constant time on average.'),
  B('dsa', 'How many edges does a tree with n nodes have?', ['n', 'n - 1', 'n + 1', '2n'], 1, 'A tree is connected and has no cycles, so it has exactly n - 1 edges.'),
  B('dsa', 'What is the time complexity of inserting a node at the head of a singly linked list?', ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'], 0, 'Only the head pointer changes, so it is constant time.'),
  B('dsa', 'Which of these sorting algorithms is stable?', ['Quick sort', 'Heap sort', 'Merge sort', 'Selection sort'], 2, 'Merge sort keeps equal elements in their original order.'),
  B('dsa', 'Which algorithm finds shortest paths from one source when all edge weights are non-negative?', ['Kruskal', 'Prim', 'Dijkstra', 'DFS'], 2, 'Dijkstra algorithm is designed for single-source shortest paths with non-negative weights.'),
  B('dsa', 'What is the postfix form of the expression A + B * C?', ['AB+C*', 'ABC*+', 'A+BC*', 'ABC+*'], 1, 'B * C is done first (BC*), then A is added: ABC*+.'),
  B('dsa', 'Which data structure is normally used to implement a priority queue?', ['Heap', 'Stack', 'Linked list only', 'Queue only'], 0, 'A binary heap gives O(log n) insert and remove of the highest priority element.'),
  B('dsa', 'What is the time complexity of merge sort in all cases?', ['O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)'], 1, 'It always divides into halves and merges in linear time, giving O(n log n).'),
  B('dsa', 'Which data structure is best for checking balanced parentheses?', ['Queue', 'Stack', 'Graph', 'Heap'], 1, 'Push an opening bracket and pop when a closing bracket arrives.'),

  B('dbms', 'Which SQL command removes all rows of a table quickly but keeps the table structure?', ['DROP', 'DELETE', 'TRUNCATE', 'REMOVE'], 2, 'TRUNCATE empties the table; DROP removes the table itself.'),
  B('dbms', 'Which statement about a primary key is correct?', ['It can contain NULL', 'It is unique and not NULL', 'It can repeat', 'A table can have many primary keys'], 1, 'A primary key uniquely identifies a row and cannot be NULL; a table has only one.'),
  B('dbms', 'Which normal form removes partial dependency?', ['1NF', '2NF', '3NF', 'BCNF'], 1, '2NF removes partial dependency on part of a composite key.'),
  B('dbms', 'In ACID, what does the letter A stand for?', ['Accuracy', 'Atomicity', 'Availability', 'Association'], 1, 'Atomicity means a transaction is done completely or not at all.'),
  B('dbms', 'Which join returns all rows from the left table and matching rows from the right?', ['INNER JOIN', 'LEFT JOIN', 'CROSS JOIN', 'SELF JOIN'], 1, 'LEFT JOIN keeps every left row and fills NULL where there is no match.'),
  B('dbms', 'Which clause is used to filter groups after GROUP BY?', ['WHERE', 'HAVING', 'ORDER BY', 'LIMIT'], 1, 'HAVING filters groups; WHERE filters rows before grouping.'),
  B('dbms', 'What is a foreign key?', ['A key that is always NULL', 'A column that refers to the primary key of another table', 'A duplicate primary key', 'An encrypted key'], 1, 'It creates a relationship between two tables.'),
  B('dbms', 'Which of these is a DDL command?', ['SELECT', 'INSERT', 'CREATE', 'UPDATE'], 2, 'CREATE, ALTER and DROP are DDL; SELECT, INSERT and UPDATE are DML.'),
  B('dbms', 'What is the main purpose of an index in a database?', ['Save disk space', 'Speed up searching', 'Encrypt data', 'Delete duplicates'], 1, 'An index lets the database find rows faster, at the cost of extra storage and slower writes.'),
  B('dbms', 'What does SELECT COUNT(*) return?', ['Number of columns', 'Number of rows', 'Sum of values', 'Number of tables'], 1, 'COUNT(*) counts all rows, including rows with NULL values.'),

  B('oops', 'What is encapsulation?', ['Hiding the code from the compiler', 'Wrapping data and methods together and controlling access', 'Creating many objects', 'Converting types'], 1, 'Encapsulation binds data and methods in a class and restricts direct access.'),
  B('oops', 'What does polymorphism mean?', ['One name, many forms', 'Many names, one form', 'Deleting objects', 'Copying objects'], 0, 'The same method call can behave differently based on the object or arguments.'),
  B('oops', 'Method overriding happens when:', ['Two methods in the same class have different parameters', 'A subclass gives its own version of a parent class method with the same signature', 'A method is deleted', 'A class has no methods'], 1, 'Overriding replaces the parent behaviour in the child class.'),
  B('oops', 'Which statement about an abstract class is correct?', ['It can be instantiated directly', 'It cannot be instantiated directly', 'It cannot have methods', 'It cannot be inherited'], 1, 'An abstract class is meant to be extended; you create objects of its subclasses.'),
  B('oops', 'Which of these is NOT a pillar of OOP?', ['Encapsulation', 'Compilation', 'Inheritance', 'Abstraction'], 1, 'The four pillars are encapsulation, abstraction, inheritance and polymorphism.'),
  B('oops', 'Method overloading is resolved at:', ['Compile time', 'Run time', 'Load time', 'Never'], 0, 'Overloading is compile-time (static) polymorphism.'),
  B('oops', 'What is the purpose of a constructor?', ['Destroy an object', 'Initialize an object when it is created', 'Print the object', 'Copy a class'], 1, 'A constructor runs automatically when an object is created.'),
  B('oops', 'What is inheritance?', ['A class acquiring properties and methods of another class', 'Hiding data', 'Creating an array of objects', 'A loop statement'], 0, 'A child class reuses and extends the parent class.'),

  B('c', 'What is the typical size of int in C on a modern 32-bit or 64-bit system?', ['1 byte', '2 bytes', '4 bytes', '8 bytes'], 2, 'On most modern compilers int is 4 bytes.'),
  B('c', 'What is the output of printf("%d", 5 / 2); in C?', ['2.5', '2', '3', '2.0'], 1, 'Both operands are integers, so integer division gives 2.'),
  B('c', 'Which function is used to allocate memory dynamically in C?', ['alloc()', 'malloc()', 'new()', 'create()'], 1, 'malloc() allocates a block of memory on the heap.'),
  B('c', 'Array indexing in C starts from:', ['0', '1', '-1', 'Any number'], 0, 'The first element is at index 0.'),
  B('c', 'What does a pointer variable store?', ['A value', 'An address', 'A character', 'A file'], 1, 'A pointer holds the memory address of another variable.'),
  B('c', 'What does strlen("abc") return?', ['2', '3', '4', '0'], 1, 'strlen counts characters before the null terminator: 3.'),
  B('c', 'What is the value of 7 % 3 in C?', ['2', '1', '0', '3'], 1, '7 divided by 3 leaves remainder 1.'),
  B('c', 'What does free(p) do?', ['Deletes the pointer variable', 'Releases the dynamically allocated memory', 'Sets memory to zero', 'Closes a file'], 1, 'free() returns heap memory to the system.'),
  B('c', 'Which header file is needed for printf and scanf?', ['stdlib.h', 'stdio.h', 'string.h', 'math.h'], 1, 'stdio.h declares the standard input and output functions.'),

  B('cpp', 'Which header is needed for cout in C++?', ['stdio.h', 'iostream', 'conio.h', 'stdlib.h'], 1, 'cout is declared in iostream.'),
  B('cpp', 'Which keyword enables runtime polymorphism in C++?', ['static', 'virtual', 'const', 'inline'], 1, 'Virtual functions are resolved at run time through the object type.'),
  B('cpp', 'What is the default access specifier of a class in C++?', ['public', 'private', 'protected', 'none'], 1, 'Class members are private by default; struct members are public by default.'),
  B('cpp', 'What is the name of a destructor for class Car?', ['Car()', '~Car()', 'delete Car', 'destroy()'], 1, 'A destructor uses the class name with a tilde.'),
  B('cpp', 'Which STL container stores unique elements in sorted order?', ['vector', 'set', 'list', 'deque'], 1, 'set keeps unique keys sorted.'),
  B('cpp', 'Which statement about a C++ reference is true?', ['It can be left uninitialized', 'It must be initialized when declared', 'It can be NULL', 'It can be reassigned to another variable'], 1, 'A reference is an alias and must be bound to a variable at declaration.'),

  B('java', 'What does the JVM execute?', ['Source code', 'Bytecode', 'Machine code only', 'HTML'], 1, 'The Java compiler produces bytecode and the JVM runs it.'),
  B('java', 'Which statement about String in Java is true?', ['It is mutable', 'It is immutable', 'It is a primitive type', 'It cannot be compared'], 1, 'Once created, a String object cannot be changed.'),
  B('java', 'Which keyword is used to inherit a class in Java?', ['implements', 'extends', 'inherits', 'super'], 1, 'A class extends another class; it implements an interface.'),
  B('java', 'What is the default value of an int instance variable in Java?', ['null', '0', '1', 'undefined'], 1, 'Numeric instance variables default to 0.'),
  B('java', 'Which collection does not allow duplicate elements?', ['ArrayList', 'HashSet', 'LinkedList', 'Vector'], 1, 'A Set stores only unique elements.'),
  B('java', 'Why is multiple inheritance of classes not allowed in Java?', ['To avoid ambiguity such as the diamond problem', 'Because it is slow', 'Because of memory limits', 'It is allowed'], 0, 'Java avoids ambiguity; multiple inheritance is done using interfaces.'),
  B('java', 'For Strings in Java, what does equals() compare?', ['Memory addresses', 'Content', 'Length only', 'Hash only'], 1, 'equals() compares the characters; == compares references.'),

  B('python', 'Which of these is mutable in Python?', ['tuple', 'string', 'list', 'int'], 2, 'Lists can be changed after creation.'),
  B('python', 'What is the output of 7 // 2 in Python?', ['3.5', '3', '4', '2'], 1, '// is floor division, giving 3.'),
  B('python', 'What is the output of 3 ** 2 in Python?', ['6', '9', '5', '32'], 1, '** is the power operator: 3 squared is 9.'),
  B('python', 'Which keyword defines a function in Python?', ['function', 'def', 'fun', 'define'], 1, 'Functions are defined with def.'),
  B('python', 'What is the type of {} in Python?', ['list', 'set', 'dict', 'tuple'], 2, 'Empty curly braces create a dictionary; use set() for an empty set.'),
  B('python', 'What is the output of "abc"[::-1]?', ['abc', 'cba', 'bca', 'error'], 1, 'A step of -1 reverses the string.'),

  B('os', 'Which of these is NOT a necessary condition for deadlock?', ['Mutual exclusion', 'Hold and wait', 'Circular wait', 'Preemption'], 3, 'The condition is no preemption; if preemption is allowed, deadlock can be avoided.'),
  B('os', 'Which scheduling algorithm uses a time quantum?', ['FCFS', 'Round Robin', 'SJF', 'Priority (non-preemptive)'], 1, 'Round Robin gives each process a fixed time slice.'),
  B('os', 'What is virtual memory?', ['Extra RAM chips', 'A technique that uses disk space to extend available memory', 'Cache memory', 'ROM'], 1, 'It lets programs use more memory than physical RAM by paging to disk.'),
  B('os', 'Which is a page replacement algorithm?', ['LRU', 'SJF', 'FCFS', 'Banker'], 0, 'LRU replaces the least recently used page.'),
  B('os', 'What do threads of the same process share?', ['Stack', 'Registers', 'Code, data and open files', 'Nothing'], 2, 'Threads share the process memory space but have their own stack and registers.'),
  B('os', 'Which scheduling algorithm gives the minimum average waiting time (for known burst times)?', ['FCFS', 'SJF', 'Round Robin', 'LIFO'], 1, 'Shortest Job First is optimal for average waiting time.'),
  B('os', 'What is thrashing?', ['Very fast CPU', 'Excessive paging that reduces performance', 'Disk failure', 'A virus'], 1, 'The system spends more time swapping pages than executing.'),
  B('os', 'What is a semaphore mainly used for?', ['Memory allocation', 'Process synchronization', 'File compression', 'Networking'], 1, 'Semaphores control access to shared resources.'),

  B('cn', 'How many layers are there in the OSI model?', ['4', '5', '7', '9'], 2, 'The OSI model has 7 layers.'),
  B('cn', 'What is the default port of HTTP?', ['21', '25', '80', '443'], 2, 'HTTP uses port 80; HTTPS uses 443.'),
  B('cn', 'Which protocol is connection-oriented?', ['UDP', 'TCP', 'IP', 'ICMP'], 1, 'TCP sets up a connection and gives reliable delivery.'),
  B('cn', 'How many bits are there in an IPv4 address?', ['16', '32', '64', '128'], 1, 'IPv4 addresses are 32 bits; IPv6 addresses are 128 bits.'),
  B('cn', 'What does DNS do?', ['Encrypts data', 'Translates domain names to IP addresses', 'Assigns MAC addresses', 'Blocks viruses'], 1, 'DNS maps names like example.com to IP addresses.'),
  B('cn', 'Which OSI layer is responsible for routing?', ['Data Link', 'Network', 'Transport', 'Session'], 1, 'The Network layer handles logical addressing and routing.'),
  B('cn', 'Which device connects different networks and forwards packets between them?', ['Hub', 'Switch', 'Router', 'Repeater'], 2, 'A router forwards packets between networks using IP addresses.'),

  B('html', 'Which HTML tag creates the largest heading?', ['h6', 'h1', 'head', 'header'], 1, 'h1 is the top-level and largest heading by default.'),
  B('css', 'Which CSS property changes the text colour?', ['font-color', 'text-color', 'color', 'foreground'], 2, 'The color property sets the text colour.'),
  B('css', 'With box-sizing: border-box, the width of an element includes:', ['Only content', 'Content, padding and border', 'Content and margin', 'Only border'], 1, 'Padding and border are counted inside the given width.'),
  B('javascript', 'What does typeof null return in JavaScript?', ['null', 'undefined', 'object', 'number'], 2, 'This is a well-known quirk of the language.'),
  B('javascript', 'Which array method adds an element at the end?', ['push', 'pop', 'shift', 'unshift'], 0, 'push adds to the end; unshift adds to the start.'),
  B('react', 'Which React hook is used to manage state in a function component?', ['useEffect', 'useState', 'useRef', 'useMemo'], 1, 'useState returns the state value and a setter function.'),
  B('react', 'Props in React are:', ['Read-only inputs from the parent', 'Editable by the child', 'Same as state', 'Global variables'], 0, 'A child component must not modify its props.'),
  B('nodejs', 'Which module system uses require() in Node.js?', ['ES modules', 'CommonJS', 'AMD', 'UMD'], 1, 'CommonJS uses require and module.exports.'),
  B('webfund', 'Which HTTP status code means Not Found?', ['200', '301', '404', '500'], 2, '404 means the requested resource was not found.'),
  B('webfund', 'Which HTTP method is normally used to create a new resource?', ['GET', 'POST', 'DELETE', 'HEAD'], 1, 'POST sends data to the server to create something.')
];