const B = (cat, question, options, answer, explanation) => ({ cat, question, options, answer, explanation });

module.exports = [
  B('dbms', 'Which SQL clause is used to sort the result set?', ['GROUP BY', 'ORDER BY', 'SORT BY', 'ARRANGE'], 1, 'ORDER BY sorts rows in ascending or descending order.'),
  B('dbms', 'Which aggregate function returns the highest value in a column?', ['TOP()', 'HIGH()', 'MAX()', 'LARGE()'], 2, 'MAX() returns the largest value.'),
  B('dbms', 'What does the UNIQUE constraint ensure?', ['All values in the column are different', 'The column can never be empty', 'The column is the primary key', 'The column is numeric'], 0, 'UNIQUE prevents duplicate values in a column.'),
  B('dbms', 'Which command adds a new column to an existing table?', ['UPDATE TABLE', 'ALTER TABLE', 'MODIFY ROW', 'INSERT COLUMN'], 1, 'ALTER TABLE ... ADD column changes the table structure.'),
  B('dbms', 'What is a transaction in a database?', ['A single column', 'A logical unit of work that is done completely or not at all', 'A backup file', 'A type of index'], 1, 'A transaction groups operations so they succeed or fail together.'),
  B('dbms', 'In ACID, what does the letter D stand for?', ['Dependency', 'Durability', 'Distribution', 'Definition'], 1, 'Durability means committed data survives crashes.'),
  B('dbms', 'Which of these is a DCL command?', ['SELECT', 'CREATE', 'INSERT', 'REVOKE'], 3, 'GRANT and REVOKE are Data Control Language commands.'),
  B('dbms', 'What is the degree of a relation?', ['Number of rows', 'Number of attributes (columns)', 'Number of keys', 'Number of tables'], 1, 'Degree is the count of columns; cardinality is the count of rows.'),
  B('dbms', 'What is the cardinality of a relation?', ['Number of tuples (rows)', 'Number of columns', 'Number of indexes', 'Number of foreign keys'], 0, 'Cardinality is the number of rows in the table.'),
  B('dbms', 'In a LIKE pattern, which wildcard matches any sequence of characters?', ['_', '%', '*', '#'], 1, '% matches zero or more characters; _ matches exactly one.'),
  B('dbms', 'What does the IN operator do in a WHERE clause?', ['Checks whether a value matches any value in a list', 'Joins two tables', 'Sorts the result', 'Inserts a row'], 0, 'WHERE city IN (a, b, c) is a short form of several OR conditions.'),
  B('dbms', 'A minimal set of attributes that uniquely identifies a row is called:', ['Super key', 'Candidate key', 'Foreign key', 'Composite attribute'], 1, 'A candidate key is a minimal super key.'),
  B('dbms', 'Which join returns only the rows that match in both tables?', ['LEFT JOIN', 'RIGHT JOIN', 'INNER JOIN', 'FULL JOIN'], 2, 'INNER JOIN keeps only matching rows.'),
  B('dbms', 'First Normal Form (1NF) requires:', ['Atomic values and no repeating groups', 'No partial dependency', 'No transitive dependency', 'Every determinant is a key'], 0, 'Each cell must hold a single value.'),
  B('dbms', 'What is a deadlock in a database?', ['A table with no rows', 'Two transactions waiting for each other to release locks', 'A slow query', 'A failed backup'], 1, 'Each transaction holds a lock the other needs, so neither can continue.'),
  B('dbms', 'What is denormalization?', ['Removing all keys', 'Adding controlled redundancy to speed up reads', 'Deleting a table', 'Encrypting data'], 1, 'It trades extra storage and update effort for faster queries.'),
  B('dbms', 'Which SQL statement changes existing rows in a table?', ['MODIFY', 'CHANGE', 'UPDATE', 'ALTER ROW'], 2, 'UPDATE table SET column = value WHERE condition.'),
  B('dbms', 'Which condition correctly finds rows where salary has no value?', ['WHERE salary = NULL', 'WHERE salary IS NULL', 'WHERE salary == NULL', 'WHERE salary EMPTY'], 1, 'NULL cannot be compared with =; use IS NULL.'),

  B('os', 'What is the kernel of an operating system?', ['A text editor', 'The core part that manages hardware and resources', 'A type of virus', 'The desktop'], 1, 'The kernel controls CPU, memory and devices.'),
  B('os', 'Which of these is NOT an operating system?', ['Linux', 'Android', 'MySQL', 'macOS'], 2, 'MySQL is a database system.'),
  B('os', 'What is a process?', ['A program stored on disk', 'A program in execution', 'A hardware device', 'A file type'], 1, 'A program becomes a process when it is running.'),
  B('os', 'What does the Process Control Block (PCB) store?', ['Information about a process such as state, program counter and registers', 'Only the process name', 'Disk files', 'Network packets'], 0, 'The OS uses the PCB to manage and switch processes.'),
  B('os', 'What is the convoy effect?', ['Many short processes waiting behind one long process in FCFS', 'Fast page replacement', 'Multiple CPUs working together', 'A disk error'], 0, 'A long CPU-bound job delays all the short jobs behind it.'),
  B('os', 'Which scheduling algorithm can cause starvation?', ['Round Robin', 'FCFS', 'Priority scheduling', 'None of these'], 2, 'Low-priority processes may wait forever if high-priority ones keep arriving.'),
  B('os', 'Aging is a technique used to:', ['Increase disk size', 'Prevent starvation by raising the priority of waiting processes', 'Delete old files', 'Speed up the clock'], 1, 'Priority slowly increases while a process waits.'),
  B('os', 'What is a critical section?', ['A part of code that accesses shared resources', 'The most important file', 'A hardware fault', 'The boot sector'], 0, 'Only one process should execute it at a time.'),
  B('os', 'What is paging?', ['Dividing memory into fixed-size blocks', 'Dividing memory into variable-size blocks', 'Copying files', 'Printing pages'], 0, 'Logical memory is split into pages and physical memory into frames of the same size.'),
  B('os', 'Segmentation divides a program into:', ['Fixed-size pages', 'Variable-size logical parts', 'Equal bytes', 'Only two parts'], 1, 'Segments follow the logical structure such as code, data and stack.'),
  B('os', 'Internal fragmentation occurs when:', ['Free memory is scattered in small holes between processes', 'Allocated memory is larger than the process needs', 'The disk is full', 'The CPU is idle'], 1, 'The unused space inside an allocated block is wasted.'),
  B('os', 'External fragmentation is caused by:', ['Fixed-size blocks only', 'Free memory split into small non-contiguous holes', 'Too many threads', 'Slow disks'], 1, 'Enough total free memory exists but not in one contiguous piece.'),
  B('os', 'Belady anomaly (more frames giving more page faults) can occur in:', ['LRU', 'Optimal', 'FIFO', 'None'], 2, 'FIFO page replacement can show this anomaly.'),
  B('os', 'What is the TLB?', ['A cache of recent page table entries', 'A type of disk', 'A scheduling queue', 'A network buffer'], 0, 'The Translation Lookaside Buffer speeds up address translation.'),
  B('os', 'Which Unix system call creates a new process?', ['exec()', 'fork()', 'wait()', 'exit()'], 1, 'fork() creates a child process that is a copy of the parent.'),
  B('os', 'What is a zombie process?', ['A process that has finished but still has an entry in the process table', 'A very slow process', 'A virus', 'A process using all memory'], 0, 'The entry stays until the parent reads the exit status.'),
  B('os', 'When the I/O a process was waiting for completes, it moves to which state?', ['Running', 'Ready', 'Terminated', 'New'], 1, 'It becomes ready and waits for the CPU.'),
  B('os', 'In preemptive scheduling:', ['The OS can take the CPU away from a running process', 'A process keeps the CPU until it finishes', 'Only one process exists', 'Processes never wait'], 0, 'Preemption allows the OS to switch processes, for example when a time slice ends.'),

  B('cn', 'Which OSI layer handles encryption and data compression?', ['Session', 'Presentation', 'Transport', 'Network'], 1, 'The Presentation layer translates, encrypts and compresses data.'),
  B('cn', 'Which device works at the Data Link layer and forwards frames using MAC addresses?', ['Hub', 'Router', 'Switch', 'Repeater'], 2, 'A switch learns MAC addresses and sends frames to the right port.'),
  B('cn', 'Which protocol automatically assigns IP addresses to devices?', ['DNS', 'DHCP', 'ARP', 'FTP'], 1, 'DHCP gives IP address, mask and gateway to hosts.'),
  B('cn', 'What is the default port of SSH?', ['21', '22', '23', '25'], 1, 'SSH uses port 22.'),
  B('cn', 'What is the default control port of FTP?', ['21', '22', '53', '110'], 0, 'FTP uses port 21 for control commands.'),
  B('cn', 'In which network topology are all devices connected to a central device?', ['Bus', 'Ring', 'Star', 'Mesh'], 2, 'Star topology connects every node to a hub or switch.'),
  B('cn', 'How many bits are there in a MAC address?', ['32', '48', '64', '128'], 1, 'A MAC address is 48 bits, usually written as six hex pairs.'),
  B('cn', 'What is the first-octet range of Class A IPv4 addresses?', ['1 to 126', '128 to 191', '192 to 223', '224 to 239'], 0, 'Class A starts with 1 to 126 (127 is reserved for loopback).'),
  B('cn', 'What is the IPv4 loopback address?', ['0.0.0.0', '127.0.0.1', '255.255.255.255', '192.168.0.1'], 1, '127.0.0.1 refers to the local machine.'),
  B('cn', 'UDP is best described as:', ['Connection-oriented and reliable', 'Connectionless and unreliable', 'Encrypted', 'Used only for email'], 1, 'UDP has no handshake and no delivery guarantee, so it is fast.'),
  B('cn', 'What is the order of the TCP three-way handshake?', ['SYN, SYN-ACK, ACK', 'ACK, SYN, FIN', 'SYN, ACK, FIN', 'FIN, ACK, SYN'], 0, 'Client sends SYN, server replies SYN-ACK, client sends ACK.'),
  B('cn', 'Which protocol provides encryption for secure web browsing?', ['HTTP', 'TLS (used by HTTPS)', 'FTP', 'SMTP'], 1, 'HTTPS is HTTP running over TLS.'),
  B('cn', 'The ping command uses which protocol?', ['TCP', 'UDP', 'ICMP', 'SMTP'], 2, 'Ping sends ICMP echo requests.'),
  B('cn', 'How many layers does the classic TCP/IP model have?', ['3', '4', '5', '7'], 1, 'Application, Transport, Internet and Network Access.'),
  B('cn', 'Which email protocol keeps messages on the server and syncs across devices?', ['POP3', 'IMAP', 'SMTP', 'FTP'], 1, 'IMAP leaves mail on the server; POP3 usually downloads it.'),
  B('cn', 'What is the subnet mask of a /24 network?', ['255.0.0.0', '255.255.0.0', '255.255.255.0', '255.255.255.255'], 2, '24 network bits give 255.255.255.0.'),

  B('oops', 'What is an object in OOP?', ['A blueprint', 'An instance of a class', 'A function', 'A file'], 1, 'An object is created from a class and holds actual data.'),
  B('oops', 'What is a class?', ['A blueprint or template for creating objects', 'A running program', 'A variable', 'A loop'], 0, 'A class defines the data and behaviour that objects will have.'),
  B('oops', 'Abstraction means:', ['Showing only essential details and hiding implementation', 'Copying an object', 'Making all data public', 'Repeating code'], 0, 'The user knows what an object does, not how it does it.'),
  B('oops', 'Which of these is compile-time polymorphism?', ['Method overriding', 'Method overloading', 'Virtual functions', 'Dynamic binding'], 1, 'Overloading is decided by the compiler from the argument list.'),
  B('oops', 'What is an interface (in Java)?', ['A class with only private data', 'A contract of abstract methods that implementing classes must define', 'A GUI window', 'A type of loop'], 1, 'Classes implement an interface and provide the method bodies.'),
  B('oops', 'A class C inherits from B and B inherits from A. This is called:', ['Single inheritance', 'Multilevel inheritance', 'Hierarchical inheritance', 'Hybrid only'], 1, 'The chain A to B to C is multilevel inheritance.'),
  B('oops', 'Which access specifier lets subclasses use a member but hides it from outside code?', ['public', 'private', 'protected', 'static'], 2, 'protected members are visible to subclasses.'),
  B('oops', 'A static member belongs to:', ['Each object separately', 'The class itself', 'Only the constructor', 'The compiler'], 1, 'All objects share one copy of a static member.'),
  B('oops', 'What does the this keyword refer to?', ['The parent class', 'The current object', 'The next object', 'The main method'], 1, 'this points to the object on which the method is called.'),
  B('oops', 'Constructor overloading means:', ['A class has multiple constructors with different parameters', 'A constructor is very large', 'A constructor calls itself', 'A class has no constructor'], 0, 'Different constructors allow objects to be created in different ways.'),
  B('oops', 'A Car has an Engine. This relationship is best described as:', ['Inheritance (is-a)', 'Composition (has-a)', 'Polymorphism', 'Overloading'], 1, 'The Car contains an Engine object, so it is a has-a relationship.'),
  B('oops', 'In the SOLID principles, what does S stand for?', ['Single Responsibility', 'Static Binding', 'Simple Syntax', 'Safe Sharing'], 0, 'A class should have only one reason to change.'),
  B('oops', 'Can a constructor have a return type?', ['Yes, int', 'Yes, void', 'No', 'Only in abstract classes'], 2, 'Constructors have no return type, not even void.'),
  B('oops', 'The diamond problem is associated with:', ['Multiple inheritance', 'Encapsulation', 'Method overloading', 'Static members'], 0, 'A class inheriting from two classes that share a parent creates ambiguity.'),

  B('cpp', 'Which operator is the scope resolution operator in C++?', ['->', '::', '.', '&&'], 1, ':: is used, for example, as ClassName::method.'),
  B('cpp', 'Which object is used to read input in C++?', ['cout', 'cin', 'print', 'scan'], 1, 'cin >> x reads input into x.'),
  B('cpp', 'What is an inline function?', ['A function the compiler may expand at the call site', 'A function defined inside main only', 'A recursive function', 'A function with no name'], 0, 'Inline expansion can avoid function call overhead.'),
  B('cpp', 'A friend function can:', ['Access private members of the class it is a friend of', 'Not access any member', 'Only access public members', 'Be called only by the class'], 0, 'friend gives a non-member function access to private data.'),
  B('cpp', 'Which declaration is a pure virtual function?', ['virtual void f();', 'virtual void f() = 0;', 'void f() = virtual;', 'pure void f();'], 1, '= 0 makes the function pure virtual and the class abstract.'),
  B('cpp', 'Which STL container adapter follows LIFO?', ['queue', 'stack', 'set', 'map'], 1, 'stack gives push, pop and top in last-in-first-out order.'),
  B('cpp', 'What does the delete operator do?', ['Frees memory allocated with new', 'Deletes a file', 'Removes a class', 'Clears the screen'], 0, 'delete releases heap memory and calls the destructor.'),
  B('cpp', 'What are default arguments in C++?', ['Values used when the caller does not pass an argument', 'Arguments that cannot change', 'Arguments passed by reference', 'Arguments of main'], 0, 'void f(int a = 5) uses 5 if no value is given.'),
  B('cpp', 'Templates in C++ are used for:', ['Generic programming that works with many data types', 'Drawing shapes', 'File handling only', 'Memory deletion'], 0, 'A template lets one function or class work with any type.'),
  B('cpp', 'Which container gives O(1) average lookup by key?', ['map', 'unordered_map', 'set', 'list'], 1, 'unordered_map is a hash table; map is a balanced tree with O(log n).'),
  B('cpp', 'Which of these operators cannot be overloaded in C++?', ['::', '+', '-', '[]'], 0, 'The scope resolution operator :: cannot be overloaded.'),
  B('cpp', 'What is the output of cout << 10 / 4; in C++?', ['2.5', '2', '3', '2.0'], 1, 'Both operands are int, so integer division gives 2.'),
  B('cpp', 'What does const after a member function declaration mean?', ['The function does not modify the object', 'The function returns a constant', 'The function is static', 'The function is virtual'], 0, 'A const member function promises not to change member data.'),
  B('cpp', 'Which of these is a smart pointer in modern C++?', ['unique_ptr', 'void_ptr', 'raw_ptr', 'auto_free'], 0, 'unique_ptr automatically releases the object it owns.'),

  B('java', 'Which keyword is used by a class to use an interface?', ['extends', 'implements', 'uses', 'imports'], 1, 'A class implements an interface.'),
  B('java', 'Which of these is NOT a primitive type in Java?', ['int', 'boolean', 'String', 'char'], 2, 'String is a class, not a primitive.'),
  B('java', 'What is the size of double in Java?', ['4 bytes', '8 bytes', '2 bytes', '16 bytes'], 1, 'double is a 64-bit (8 byte) type.'),
  B('java', 'What does garbage collection do in Java?', ['Automatically frees memory of unreachable objects', 'Deletes source files', 'Compiles code', 'Closes the program'], 0, 'The JVM reclaims heap memory that is no longer referenced.'),
  B('java', 'Which keyword prevents a method from being overridden?', ['static', 'final', 'abstract', 'private static'], 1, 'A final method cannot be overridden in a subclass.'),
  B('java', 'Which class is the parent of all classes in Java?', ['Main', 'Object', 'Class', 'Parent'], 1, 'Every class directly or indirectly extends Object.'),
  B('java', 'Java is called platform independent because:', ['It compiles to bytecode that runs on any JVM', 'It runs only on Windows', 'It has no compiler', 'It needs no memory'], 0, 'The same bytecode runs on any system that has a JVM.'),
  B('java', 'Which of these is a checked exception?', ['NullPointerException', 'IOException', 'ArithmeticException', 'ArrayIndexOutOfBoundsException'], 1, 'IOException must be handled or declared at compile time.'),
  B('java', 'Which collection keeps insertion order and allows duplicates?', ['HashSet', 'TreeSet', 'ArrayList', 'HashMap'], 2, 'ArrayList is an ordered list that permits duplicates.'),
  B('java', 'How many null keys can a HashMap have?', ['None', 'One', 'Two', 'Unlimited'], 1, 'HashMap allows a single null key and many null values.'),
  B('java', 'Which keyword refers to the parent class in Java?', ['this', 'super', 'parent', 'base'], 1, 'super is used to call parent constructors and methods.'),
  B('java', 'A static method in Java can be called:', ['Without creating an object of the class', 'Only through an object', 'Only inside constructors', 'Never from main'], 0, 'Static methods belong to the class, so ClassName.method() works.'),

  B('c', 'Which is the correct way to declare a pointer to an int in C?', ['int p*;', 'int *p;', 'pointer int p;', 'int &p;'], 1, 'The * in the declaration makes p a pointer to int.'),
  B('c', 'What does the break statement do inside a loop?', ['Skips the current iteration', 'Exits the loop immediately', 'Restarts the loop', 'Ends the program'], 1, 'break jumps out of the nearest loop or switch.'),
  B('c', 'Which function is safest for reading a line of text with spaces in C?', ['gets', 'fgets', 'scanf with %d', 'getchar only'], 1, 'fgets limits the number of characters read; gets is unsafe.'),
  B('c', 'What does return 0 from main usually indicate?', ['An error', 'Successful execution', 'Infinite loop', 'Memory leak'], 1, 'A zero exit status means the program finished successfully.'),
  B('c', 'What is a NULL pointer?', ['A pointer that points to nothing', 'A pointer to zero bytes of data', 'A pointer to the stack', 'A pointer to a string'], 0, 'A NULL pointer does not refer to any valid object.'),
  B('c', 'What is the typical value of sizeof(double) in C?', ['2', '4', '8', '16'], 2, 'double is normally 8 bytes.'),
  B('c', 'Which storage class keeps a local variable value between function calls?', ['auto', 'register', 'static', 'extern'], 2, 'A static local variable is initialized once and keeps its value.'),
  B('c', 'How is calloc different from malloc?', ['calloc initializes the allocated memory to zero', 'calloc frees memory', 'calloc is faster always', 'There is no difference'], 0, 'calloc(n, size) allocates and zeroes the memory.')
];