const B = (cat, question, options, answer, explanation) => ({ cat, question, options, answer, explanation });

module.exports = [
  B('aptitude', 'What is 15% of 240?', ['30', '36', '40', '42'], 1, '240 x 15/100 = 36.'),
  B('aptitude', 'A price rises from Rs. 80 to Rs. 100. What is the percentage increase?', ['20%', '25%', '30%', '15%'], 1, 'Increase 20 on 80 = 25%.'),
  B('aptitude', 'A shirt marked at Rs. 800 is sold at a 25% discount. What is the selling price?', ['600', '620', '640', '700'], 0, '800 x 75/100 = 600.'),
  B('aptitude', 'Cost price is Rs. 400 and selling price is Rs. 500. What is the profit percentage?', ['20%', '25%', '30%', '15%'], 1, 'Profit 100 on cost 400 = 25%.'),
  B('aptitude', 'An article is sold at a 10% loss for Rs. 450. What was its cost price?', ['480', '500', '550', '405'], 1, 'CP = 450 / 0.9 = 500.'),
  B('aptitude', 'What is the simple interest on Rs. 4000 at 5% per annum for 3 years?', ['500', '600', '700', '800'], 1, '4000 x 5 x 3 / 100 = 600.'),
  B('aptitude', 'What is the compound interest on Rs. 1000 at 10% per annum for 2 years?', ['200', '210', '220', '121'], 1, 'Amount = 1000 x 1.1 x 1.1 = 1210, so CI = 210.'),
  B('aptitude', 'Two parts are in the ratio 2:3 and the total is 250. What is the larger part?', ['100', '150', '120', '130'], 1, '3/5 of 250 = 150.'),
  B('aptitude', 'What is the average of 10, 20, 30, 40 and 50?', ['25', '30', '35', '40'], 1, 'Sum 150 divided by 5 = 30.'),
  B('aptitude', 'The average of 4 numbers is 25. A fifth number 50 is added. What is the new average?', ['28', '30', '32', '35'], 1, '(100 + 50) / 5 = 30.'),
  B('aptitude', 'A can do a work in 12 days and B in 24 days. How many days will they take together?', ['6', '8', '9', '10'], 1, '1/12 + 1/24 = 1/8, so 8 days.'),
  B('aptitude', 'One pipe fills a tank in 6 hours and another empties it in 12 hours. If both are open, how long to fill the tank?', ['8', '10', '12', '18'], 2, 'Net rate = 1/6 - 1/12 = 1/12, so 12 hours.'),
  B('aptitude', 'A car moves at 60 km/h. How far does it go in 2.5 hours?', ['120 km', '150 km', '160 km', '180 km'], 1, '60 x 2.5 = 150.'),
  B('aptitude', 'Trains 100 m and 150 m long run in opposite directions at 60 km/h and 40 km/h. How long do they take to cross each other?', ['6 s', '9 s', '10 s', '12 s'], 1, 'Relative speed 100 km/h = 250/9 m/s; distance 250 m gives 9 s.'),
  B('aptitude', 'A boat goes 12 km/h in still water and the stream is 3 km/h. What is its downstream speed?', ['9', '12', '15', '18'], 2, 'Downstream = 12 + 3 = 15 km/h.'),
  B('aptitude', 'What is the HCF of 12 and 18?', ['3', '6', '9', '12'], 1, 'Common factors of 12 and 18: the greatest is 6.'),
  B('aptitude', 'What is the LCM of 4, 6 and 8?', ['12', '24', '36', '48'], 1, 'The smallest number divisible by all three is 24.'),
  B('aptitude', 'A father is 3 times as old as his son. The sum of their ages is 48. How old is the son?', ['10', '12', '14', '16'], 1, 'Son x, father 3x, 4x = 48, so x = 12.'),
  B('aptitude', 'In how many ways can 3 people stand in a row?', ['3', '6', '9', '12'], 1, '3! = 6.'),
  B('aptitude', 'What is the value of 5C2?', ['5', '10', '15', '20'], 1, '5!/(2! x 3!) = 10.'),
  B('aptitude', 'What is the probability of getting a head in one toss of a fair coin?', ['1/4', '1/3', '1/2', '1'], 2, 'One favourable outcome out of two.'),
  B('aptitude', 'Two dice are thrown. What is the probability that the sum is 7?', ['1/12', '1/6', '1/9', '1/4'], 1, '6 favourable outcomes out of 36 = 1/6.'),
  B('aptitude', 'What is the area of a circle of radius 7 cm? (use pi = 22/7)', ['44', '154', '308', '49'], 1, 'Area = 22/7 x 7 x 7 = 154.'),
  B('aptitude', 'What is the perimeter of a rectangle 12 cm long and 8 cm wide?', ['20', '32', '40', '96'], 2, '2 x (12 + 8) = 40.'),
  B('aptitude', 'What is the angle between the hour and minute hands at 3:00?', ['60', '75', '90', '120'], 2, 'At 3:00 the hands are 3 hours apart: 3 x 30 = 90 degrees.'),
  B('aptitude', 'Simplify: 100 - 20 x 4 / 8 + 5', ['95', '105', '110', '15'], 0, 'By BODMAS: 20 x 4 = 80, 80 / 8 = 10, 100 - 10 + 5 = 95.'),
  B('aptitude', 'What is the value of 2^3 x 2^4?', ['64', '128', '256', '32'], 1, '2^(3+4) = 2^7 = 128.'),
  B('aptitude', 'What is the unit digit of 7^4?', ['1', '3', '7', '9'], 0, '7^4 = 2401, so the unit digit is 1.'),
  B('aptitude', 'What is the smallest number divisible by 2, 3, 4 and 5?', ['30', '60', '90', '120'], 1, 'LCM of 2, 3, 4, 5 is 60.'),
  B('aptitude', 'Rice at Rs. 20/kg and Rs. 30/kg is mixed in equal quantities. What is the price per kg of the mixture?', ['24', '25', '26', '27'], 1, 'Mean of 20 and 30 = 25.'),
  B('aptitude', 'In a pie chart, what angle represents 25%?', ['45', '90', '120', '180'], 1, '25% of 360 = 90 degrees.'),
  B('aptitude', 'If x + 5 = 12, what is x squared?', ['14', '42', '49', '64'], 2, 'x = 7 and 7^2 = 49.'),
  B('aptitude', 'A man goes 120 km at 40 km/h and returns at 60 km/h. What is his average speed?', ['48', '50', '52', '45'], 0, 'Average speed = 2 x 40 x 60 / (40 + 60) = 48.'),
  B('aptitude', 'A sum becomes double in 5 years at simple interest. What is the rate per annum?', ['10%', '15%', '20%', '25%'], 2, 'Interest = principal in 5 years, so rate = 100/5 = 20%.'),
  B('aptitude', 'A is 45 years old now. Five years ago A was twice as old as B. How old is B now?', ['20', '25', '30', '35'], 1, 'Five years ago A was 40, so B was 20 and is 25 now.'),

  B('reasoning', 'Find the next number: 5, 10, 20, 40, ?', ['60', '70', '80', '100'], 2, 'Each number doubles.'),
  B('reasoning', 'Find the next number: 1, 1, 2, 3, 5, 8, ?', ['11', '12', '13', '14'], 2, 'Fibonacci: 5 + 8 = 13.'),
  B('reasoning', 'Find the next number: 2, 5, 10, 17, 26, ?', ['35', '36', '37', '38'], 2, 'Differences are 3, 5, 7, 9, so next difference is 11: 26 + 11 = 37.'),
  B('reasoning', 'Find the next number: 3, 6, 11, 18, 27, ?', ['36', '38', '40', '42'], 1, 'Differences 3, 5, 7, 9, then 11: 27 + 11 = 38.'),
  B('reasoning', 'Find the next letter: A, C, F, J, O, ?', ['T', 'U', 'V', 'W'], 1, 'Gaps are +2, +3, +4, +5, +6: O + 6 = U.'),
  B('reasoning', 'If CAT is coded as DBU, how is DOG coded?', ['EPH', 'ENH', 'EPG', 'DPH'], 0, 'Each letter moves one step forward.'),
  B('reasoning', 'If MOON is coded as NPPO, how is STAR coded?', ['TUBS', 'TVBS', 'SUBS', 'TUAS'], 0, 'Each letter moves one step forward: S-T, T-U, A-B, R-S.'),
  B('reasoning', 'Pointing to a woman, Ravi says she is the daughter of the only son of his grandfather. How is she related to Ravi?', ['Mother', 'Sister', 'Aunt', 'Cousin'], 1, 'The only son of Ravi grandfather is Ravi father; his daughter is Ravi sister.'),
  B('reasoning', 'A mother brother is B. B daughter is C. How is C related to A?', ['Sister', 'Cousin', 'Aunt', 'Niece'], 1, 'Mother brother is the maternal uncle and his daughter is a cousin.'),
  B('reasoning', 'A man walks 5 km north, then 3 km east, then 5 km south. How far is he from the start?', ['3 km', '5 km', '8 km', '13 km'], 0, 'North and south cancel, leaving 3 km east.'),
  B('reasoning', 'A person faces east and turns right, then right again. Which direction is he facing now?', ['North', 'South', 'West', 'East'], 2, 'East, right turn is south, another right turn is west.'),
  B('reasoning', 'Rahul is 7th from the top in a class of 30. What is his rank from the bottom?', ['22', '23', '24', '25'], 2, '30 - 7 + 1 = 24.'),
  B('reasoning', 'Ravi is 12th from the left in a row of 30. What is his position from the right?', ['18', '19', '20', '21'], 1, '30 - 12 + 1 = 19.'),
  B('reasoning', 'Find the odd one out.', ['Apple', 'Mango', 'Potato', 'Banana'], 2, 'Potato is a vegetable; the others are fruits.'),
  B('reasoning', 'Find the odd one out: 8, 27, 64, 100', ['8', '27', '64', '100'], 3, '8, 27 and 64 are cubes; 100 is not.'),
  B('reasoning', 'Book is to Reading as Fork is to ?', ['Cooking', 'Eating', 'Writing', 'Drinking'], 1, 'A book is used for reading and a fork for eating.'),
  B('reasoning', 'Doctor is to Hospital as Teacher is to ?', ['Student', 'School', 'Book', 'Class'], 1, 'A doctor works in a hospital and a teacher in a school.'),
  B('reasoning', 'All cats are animals. All animals are living things. Conclusion: All cats are living things.', ['Definitely true', 'Definitely false', 'Cannot be determined', 'Only some are'], 0, 'Cats are inside animals, which are inside living things.'),
  B('reasoning', 'Some pens are books. All books are papers. Conclusion: Some pens are papers.', ['Definitely true', 'Definitely false', 'Cannot be determined', 'None of these'], 0, 'The pens that are books are also papers.'),
  B('reasoning', 'In a class of 50, 30 like tea, 25 like coffee and 10 like both. How many like neither?', ['0', '5', '10', '15'], 1, '30 + 25 - 10 = 45 like at least one, so 5 like neither.'),
  B('reasoning', 'A cube painted on all faces is cut into 27 equal small cubes. How many have exactly 2 faces painted?', ['8', '12', '6', '1'], 1, 'Edge cubes: 12 x (3 - 2) = 12.'),
  B('reasoning', 'If A means +, B means -, C means x, what is 8 C 3 A 4 B 2?', ['22', '26', '28', '30'], 1, '8 x 3 + 4 - 2 = 26.'),
  B('reasoning', 'What is the age of Ravi? I. Ravi is 5 years older than Sita. II. Sita is 20 years old.', ['I alone is enough', 'II alone is enough', 'Both together are needed', 'Neither is enough'], 2, 'Both statements together give 20 + 5 = 25.'),
  B('reasoning', 'Five people A, B, C, D, E sit in a row. A is to the left of B, B to the left of C, D is at the extreme left and E at the extreme right. Who is in the middle?', ['A', 'B', 'C', 'D'], 1, 'The order is D, A, B, C, E, so B is in the middle.'),
  B('reasoning', 'If 2 # 3 = 13 and 3 # 4 = 25, then 4 # 5 = ?', ['31', '36', '41', '45'], 2, 'a # b = a^2 + b^2: 16 + 25 = 41.'),
  B('reasoning', 'Find the next number: 7, 14, 28, 56, ?', ['98', '112', '120', '84'], 1, 'Each number doubles.'),
  B('reasoning', 'Find the next number: 3, 9, 27, 81, ?', ['162', '216', '243', '324'], 2, 'Each number is multiplied by 3.'),

  B('verbal', 'Choose the correct option: He ___ playing since morning.', ['is', 'has been', 'was', 'had'], 1, 'Present perfect continuous with since.'),
  B('verbal', 'She is very good ___ mathematics.', ['in', 'at', 'on', 'with'], 1, 'The correct phrase is good at.'),
  B('verbal', 'Choose the synonym of Rapid.', ['Slow', 'Quick', 'Weak', 'Lazy'], 1, 'Rapid means quick.'),
  B('verbal', 'Choose the antonym of Generous.', ['Kind', 'Stingy', 'Rich', 'Polite'], 1, 'Stingy is the opposite of generous.'),
  B('verbal', 'Change to passive voice: She writes a letter.', ['A letter is written by her.', 'A letter was written by her.', 'A letter written by her.', 'She is written a letter.'], 0, 'Present simple active becomes is or are plus past participle.'),
  B('verbal', 'Change to indirect speech: He said, "I am tired."', ['He said that he is tired.', 'He said that he was tired.', 'He said I was tired.', 'He says he tired.'], 1, 'Am changes to was and I changes to he.'),
  B('verbal', 'Choose the correct sentence.', ['Each of the students have submitted the form.', 'Each of the students has submitted the form.', 'Each of the students are submitting the form.', 'Each students has submitted the form.'], 1, 'Each takes a singular verb.'),
  B('verbal', 'I have been waiting ___ 9 o clock.', ['for', 'since', 'from', 'at'], 1, 'Since is used with a point in time.'),
  B('verbal', 'What does the idiom a piece of cake mean?', ['Something delicious', 'Something very easy', 'A small gift', 'A difficult task'], 1, 'It means something very easy.'),
  B('verbal', 'What does the idiom once in a blue moon mean?', ['Very often', 'Very rarely', 'At night', 'Every month'], 1, 'It means very rarely.'),
  B('verbal', 'One word for a person who loves books.', ['Bibliophile', 'Philanthropist', 'Misanthrope', 'Optimist'], 0, 'A bibliophile loves books.'),
  B('verbal', 'One word for the fear of heights.', ['Claustrophobia', 'Acrophobia', 'Hydrophobia', 'Xenophobia'], 1, 'Acrophobia is the fear of heights.'),
  B('verbal', 'Choose the correct spelling.', ['Recieve', 'Receive', 'Receeve', 'Recive'], 1, 'Remember: i before e except after c.'),
  B('verbal', 'Fill in the blank: ___ university is in the city.', ['An', 'A', 'The an', 'No article'], 1, 'University starts with a consonant sound, so use a.'),
  B('verbal', 'Choose the antonym of Ancient.', ['Old', 'Modern', 'Historic', 'Aged'], 1, 'Modern is the opposite of ancient.'),
  B('verbal', 'Choose the synonym of Ample.', ['Little', 'Plenty', 'Small', 'Empty'], 1, 'Ample means plenty.'),
  B('verbal', 'Neither the teacher nor the students ___ present.', ['was', 'were', 'is', 'has'], 1, 'The verb agrees with the nearer subject, students, which is plural.'),
  B('verbal', 'If I ___ you, I would apologise.', ['am', 'was', 'were', 'be'], 2, 'Use were in the unreal conditional.'),
  B('verbal', 'The furniture in the room ___ old.', ['are', 'is', 'were', 'have'], 1, 'Furniture is an uncountable noun and takes a singular verb.'),
  B('verbal', 'He is afraid ___ dogs.', ['from', 'of', 'with', 'at'], 1, 'The correct phrase is afraid of.'),
  B('verbal', 'What is the meaning of Procrastinate?', ['Hurry', 'Delay doing something', 'Praise', 'Forget'], 1, 'To procrastinate is to delay doing something.'),
  B('verbal', 'Arrange the sentences. P: Then she went to the market. Q: Meena woke up early. R: She bought vegetables. S: She got ready.', ['PQRS', 'QSPR', 'SQPR', 'QPSR'], 1, 'The natural order is woke up, got ready, went to market, bought vegetables.'),
  B('verbal', 'Choose the correct sentence.', ['He dont like tea.', 'He doesnt likes tea.', 'He does not like tea.', 'He not like tea.'], 2, 'With he use does not plus the base form of the verb.'),
  B('verbal', 'Passage: Water is essential for life. Plants and animals both need it to survive. Saving water is a duty for all people. What is the main idea?', ['Water is costly', 'Water should be saved because all life needs it', 'Plants need more water than animals', 'Rain is decreasing'], 1, 'The passage stresses that life depends on water and it must be saved.'),
  B('verbal', 'By next year, she ___ her degree.', ['completes', 'will have completed', 'has completed', 'completed'], 1, 'Future perfect is used for an action finished before a future time.')
];